version: '4.12.0'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/posgressql

volumes:
  db: